import type { FeatureDefinition } from '../types';

export const BUSINESS_FEATURES: readonly FeatureDefinition[] = [
  {
    id: 'business.dashboard',
    name: 'Dashboard',
    description: 'Role-aware executive dashboard and widgets.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'business',
    tags: ['workspace'],
    capabilities: ['dashboard'],
    permissions: ['dashboard:view'],
  },
  {
    id: 'business.crm',
    name: 'CRM',
    description: 'Leads, opportunities and customer relationships.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'business',
    tags: ['crm'],
    capabilities: ['crm'],
    permissions: ['crm:view', 'crm:manage'],
  },
  {
    id: 'business.sales',
    name: 'Sales',
    description: 'Quotes, orders and sales pipeline.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'business',
    tags: ['sales'],
    capabilities: ['crm', 'ecommerce'],
    permissions: ['sales:view', 'sales:manage'],
    dependencies: ['business.crm'],
  },
  {
    id: 'business.inventory',
    name: 'Inventory',
    description: 'Stock, movements and reorder management.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'business',
    tags: ['inventory'],
    capabilities: ['inventory'],
    permissions: ['inventory:view', 'inventory:manage'],
  },
  {
    id: 'business.procurement',
    name: 'Procurement',
    description: 'Suppliers, purchase orders and receiving.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'business',
    tags: ['procurement'],
    capabilities: ['procurement'],
    permissions: ['procurement:view', 'procurement:manage'],
  },
  {
    id: 'business.accounting',
    name: 'Accounting',
    description: 'Ledger, journal, payables and receivables.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'finance',
    tags: ['accounting'],
    capabilities: ['accounting'],
    permissions: ['accounting:view', 'accounting:manage'],
  },
  {
    id: 'business.finance',
    name: 'Finance',
    description: 'Payments, trial balance and revenue.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'finance',
    tags: ['finance'],
    capabilities: ['finance', 'accounting'],
    permissions: ['finance:view', 'finance:manage'],
    dependencies: ['business.accounting'],
  },
  {
    id: 'business.manufacturing',
    name: 'Manufacturing',
    description: 'Production orders and work-in-progress.',
    category: 'business',
    scope: 'workspace',
    status: 'beta',
    version: '1.0.0',
    owner: 'business',
    tags: ['manufacturing'],
    capabilities: ['manufacturing'],
    permissions: ['manufacturing:view', 'manufacturing:manage'],
    dependencies: ['business.inventory'],
  },
  {
    id: 'business.hr',
    name: 'HR',
    description: 'People, attendance and leave management.',
    category: 'business',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'people',
    tags: ['hr'],
    capabilities: ['hr'],
    permissions: ['hr:view', 'hr:manage'],
  },
  {
    id: 'business.payroll',
    name: 'Payroll',
    description: 'Salary and payroll processing.',
    category: 'business',
    scope: 'workspace',
    status: 'beta',
    version: '1.0.0',
    owner: 'people',
    tags: ['payroll'],
    capabilities: ['payroll', 'hr'],
    permissions: ['payroll:view', 'payroll:manage'],
    dependencies: ['business.hr'],
  },
  {
    id: 'business.pos',
    name: 'Point of Sale',
    description: 'Front-of-house sales for retail and restaurant.',
    category: 'business',
    scope: 'workspace',
    status: 'beta',
    version: '1.0.0',
    owner: 'business',
    tags: ['pos'],
    capabilities: ['pos'],
    permissions: ['pos:use'],
  },
  {
    id: 'business.ecommerce',
    name: 'E-Commerce',
    description: 'Online storefront and orders.',
    category: 'business',
    scope: 'workspace',
    status: 'preview',
    version: '1.0.0',
    owner: 'business',
    tags: ['ecommerce'],
    capabilities: ['ecommerce'],
    permissions: ['ecommerce:view', 'ecommerce:manage'],
  },
] as const satisfies readonly FeatureDefinition[];

/** Lookup over the business catalog. */
export const BUSINESS_FEATURES_BY_ID: ReadonlyMap<string, FeatureDefinition> = new Map(
  BUSINESS_FEATURES.map((feature) => [feature.id, feature]),
);