import type { FeatureDefinition } from '../types';

export const EXTENSIBILITY_FEATURES: readonly FeatureDefinition[] = [
  {
    id: 'dev.api',
    name: 'API & Webhooks',
    description: 'Programmatic access and outbound webhooks.',
    category: 'developer',
    scope: 'organization',
    status: 'beta',
    version: '1.0.0',
    owner: 'developer',
    tags: ['api', 'webhooks'],
    capabilities: ['platform'],
  },
  {
    id: 'dev.developer-sdk',
    name: 'Developer SDK',
    description: 'SDK for building against the Business OS.',
    category: 'developer',
    scope: 'organization',
    status: 'preview',
    version: '1.0.0',
    owner: 'developer',
    tags: ['sdk'],
  },
  {
    id: 'ext.plugins',
    name: 'Plugin Registry',
    description: 'Third-party and custom plugin runtime.',
    category: 'plugin',
    scope: 'organization',
    status: 'experimental',
    version: '1.0.0',
    owner: 'platform',
    tags: ['plugin'],
    dependencies: ['dev.developer-sdk'],
  },
  {
    id: 'ext.integrations',
    name: 'Integrations',
    description: 'Third-party service connectors.',
    category: 'integration',
    scope: 'organization',
    status: 'beta',
    version: '1.0.0',
    owner: 'integration',
    tags: ['integrations'],
    dependencies: ['dev.api'],
  },
  {
    id: 'admin.organizations',
    name: 'Organization Administration',
    description: 'Manage organizations, members and subscriptions.',
    category: 'administration',
    scope: 'organization',
    status: 'stable',
    version: '1.0.0',
    owner: 'admin',
    tags: ['admin'],
    capabilities: ['administration'],
    permissions: ['admin:manage'],
  },
  {
    id: 'admin.plan-billing',
    name: 'Plans & Billing',
    description: 'Plans, billing and usage limits.',
    category: 'administration',
    scope: 'organization',
    status: 'preview',
    version: '1.0.0',
    owner: 'billing',
    tags: ['billing'],
    entitlements: ['billing'],
  },
  {
    id: 'infra.monitoring',
    name: 'Monitoring',
    description: 'Health, status and operational telemetry.',
    category: 'infrastructure',
    scope: 'platform',
    status: 'internal',
    version: '1.0.0',
    owner: 'infrastructure',
    internal: true,
    tags: ['infra', 'observability'],
  },
  {
    id: 'infra.notifications',
    name: 'Notifications',
    description: 'In-app and cross-channel notifications.',
    category: 'infrastructure',
    scope: 'platform',
    status: 'beta',
    version: '1.0.0',
    owner: 'infrastructure',
    tags: ['notifications'],
  },
  {
    id: 'infra.storage',
    name: 'Storage',
    description: 'Object and file storage for the workspace.',
    category: 'infrastructure',
    scope: 'workspace',
    status: 'beta',
    version: '1.0.0',
    owner: 'infrastructure',
    tags: ['storage'],
    entitlements: ['storage'],
  },
  {
    id: 'infra.search',
    name: 'Search',
    description: 'Full-text and cross-module search.',
    category: 'infrastructure',
    scope: 'workspace',
    status: 'preview',
    version: '1.0.0',
    owner: 'infrastructure',
    tags: ['search'],
  },
  {
    id: 'infra.audit-events',
    name: 'Event Bus & Audit',
    description: 'Domain events and audit streaming.',
    category: 'infrastructure',
    scope: 'platform',
    status: 'internal',
    version: '1.0.0',
    owner: 'infrastructure',
    internal: true,
    tags: ['events', 'audit'],
    dependencies: ['platform.audit'],
  },
  {
    id: 'ext.feature-flags',
    name: 'Feature Flags',
    description: 'Runtime toggles for feature rollout (future).',
    category: 'infrastructure',
    scope: 'workspace',
    status: 'hidden',
    version: '1.0.0',
    owner: 'platform',
    hidden: true,
    tags: ['flags'],
  },
] as const satisfies readonly FeatureDefinition[];

/** Lookup over the extensibility catalog. */
export const EXTENSIBILITY_FEATURES_BY_ID: ReadonlyMap<string, FeatureDefinition> = new Map(
  EXTENSIBILITY_FEATURES.map((feature) => [feature.id, feature]),
);