import type { FeatureDefinition } from '../types';

export const INTELLIGENCE_FEATURES: readonly FeatureDefinition[] = [
  {
    id: 'intelligence.ai',
    name: 'AI Assistant',
    description: 'Copilot assistance across the workspace.',
    category: 'ai',
    scope: 'workspace',
    status: 'experimental',
    version: '1.0.0',
    owner: 'ai',
    tags: ['ai', 'copilot'],
    capabilities: ['ai'],
    entitlements: ['ai'],
  },
  {
    id: 'intelligence.ai-actions',
    name: 'AI Copilot Actions',
    description: 'Contextual smart actions and suggestions.',
    category: 'ai',
    scope: 'workspace',
    status: 'experimental',
    version: '1.0.0',
    owner: 'ai',
    tags: ['ai'],
    capabilities: ['ai'],
    entitlements: ['ai'],
    dependencies: ['intelligence.ai'],
  },
  {
    id: 'intelligence.workflow',
    name: 'Workflow',
    description: 'Declarative multi-step business workflows.',
    category: 'workflow',
    scope: 'workspace',
    status: 'experimental',
    version: '1.0.0',
    owner: 'workflow',
    tags: ['workflow'],
    capabilities: ['workflow'],
    dependencies: ['intelligence.automation'],
  },
  {
    id: 'intelligence.automation',
    name: 'Automation',
    description: 'Rule-driven and scheduled automation.',
    category: 'automation',
    scope: 'workspace',
    status: 'experimental',
    version: '1.0.0',
    owner: 'workflow',
    tags: ['automation'],
    capabilities: ['workflow'],
  },
  {
    id: 'intelligence.reporting',
    name: 'Reporting',
    description: 'Reports, exports and scheduled digests.',
    category: 'reporting',
    scope: 'workspace',
    status: 'beta',
    version: '1.0.0',
    owner: 'analytics',
    tags: ['reporting'],
    capabilities: ['reports'],
    permissions: ['reports:view', 'reports:export'],
  },
  {
    id: 'intelligence.analytics',
    name: 'Analytics',
    description: 'Dashboards, metrics and business intelligence.',
    category: 'analytics',
    scope: 'workspace',
    status: 'beta',
    version: '1.0.0',
    owner: 'analytics',
    tags: ['analytics'],
    capabilities: ['analytics'],
    permissions: ['analytics:view'],
    dependencies: ['intelligence.reporting'],
  },
] as const satisfies readonly FeatureDefinition[];

/** Lookup over the intelligence catalog. */
export const INTELLIGENCE_FEATURES_BY_ID: ReadonlyMap<string, FeatureDefinition> = new Map(
  INTELLIGENCE_FEATURES.map((feature) => [feature.id, feature]),
);