import type { FeatureDefinition } from '../types';

export const PLATFORM_FEATURES: readonly FeatureDefinition[] = [
  {
    id: 'platform.core',
    name: 'Platform Core',
    description: 'The platform kernel, engine registry and lifecycle.',
    category: 'platform',
    scope: 'platform',
    status: 'stable',
    version: '1.0.0',
    owner: 'platform',
    tags: ['kernel'],
    capabilities: ['platform'],
  },
  {
    id: 'platform.workspaces',
    name: 'Workspaces',
    description: 'Multi-workspace isolation and context.',
    category: 'platform',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'platform',
    tags: ['workspace'],
    capabilities: ['platform'],
  },
  {
    id: 'platform.roles',
    name: 'Role Profiles',
    description: 'Role-based workspace profiles and module scope.',
    category: 'platform',
    scope: 'workspace',
    status: 'stable',
    version: '1.0.0',
    owner: 'platform',
    tags: ['roles'],
    capabilities: ['administration'],
    permissions: ['roles:view', 'roles:manage'],
  },
  {
    id: 'platform.theming',
    name: 'Design System & Theming',
    description: 'Design tokens and theme resolution for the workspace.',
    category: 'platform',
    scope: 'workspace',
    status: 'beta',
    version: '1.0.0',
    owner: 'design-system',
    tags: ['design', 'tokens'],
  },
  {
    id: 'platform.localization',
    name: 'Localization',
    description: 'Locale and timezone context across the workspace.',
    category: 'platform',
    scope: 'workspace',
    status: 'preview',
    version: '1.0.0',
    owner: 'platform',
    tags: ['i18n'],
  },
  {
    id: 'platform.audit',
    name: 'Audit Trail',
    description: 'Immutable audit logging of platform and business actions.',
    category: 'security',
    scope: 'organization',
    status: 'beta',
    version: '1.0.0',
    owner: 'security',
    tags: ['audit', 'compliance'],
    capabilities: ['administration'],
    permissions: ['audit:view'],
  },
  {
    id: 'platform.security',
    name: 'Security & Access Control',
    description: 'Authentication, authorization and permission evaluation.',
    category: 'security',
    scope: 'organization',
    status: 'stable',
    version: '1.0.0',
    owner: 'security',
    tags: ['security', 'rbac'],
    capabilities: ['administration'],
  },
] as const satisfies readonly FeatureDefinition[];

/** Lookup over the platform catalog. */
export const PLATFORM_FEATURES_BY_ID: ReadonlyMap<string, FeatureDefinition> = new Map(
  PLATFORM_FEATURES.map((feature) => [feature.id, feature]),
);