import {
  Banknote,
  BarChart3,
  BookOpen,
  Bot,
  Building2,
  Calculator,
  Contact,
  CreditCard,
  FileText,
  History,
  LayoutDashboard,
  Package,
  Scale,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Users2,
  UsersRound,
  Wallet,
  Warehouse,
} from 'lucide-react';

import type { ModuleManifest } from './types';

export const MODULE_MANIFESTS: ModuleManifest[] = [
  {
    id: 'dashboard',
    name: 'Overview',
    icon: LayoutDashboard,
    category: 'Workspace',
    route: '/dashboard',
    permissions: ['dashboard.read'],
    capabilities: ['dashboard', 'analytics'],
    status: 'stable',
    settings: { quickAccess: true },
    visibility: { always: true },
  },
  {
    id: 'customers',
    name: 'Customers',
    icon: UsersRound,
    category: 'Relations',
    route: '/customers',
    permissions: ['customers.read'],
    capabilities: ['crm'],
    status: 'stable',
  },
  {
    id: 'suppliers',
    name: 'Suppliers',
    icon: Building2,
    category: 'Relations',
    route: '/suppliers',
    permissions: ['suppliers.read'],
    capabilities: ['procurement'],
    status: 'stable',
  },
  {
    id: 'crm',
    name: 'CRM & Leads',
    icon: Contact,
    category: 'Relations',
    route: '/crm',
    permissions: ['crm.read'],
    capabilities: ['crm'],
    status: 'stable',
  },
  {
    id: 'products',
    name: 'Products',
    icon: Package,
    category: 'Operations',
    route: '/products',
    permissions: ['products.read'],
    capabilities: ['inventory'],
    status: 'stable',
  },
  {
    id: 'inventory',
    name: 'Inventory',
    icon: Warehouse,
    category: 'Operations',
    route: '/inventory',
    permissions: ['inventory.read'],
    capabilities: ['inventory'],
    status: 'stable',
  },
  {
    id: 'sales',
    name: 'Sales Orders',
    icon: ShoppingCart,
    category: 'Operations',
    route: '/sales',
    permissions: ['sales.read'],
    capabilities: ['pos', 'ecommerce', 'analytics'],
    status: 'stable',
  },
  {
    id: 'purchases',
    name: 'Purchases',
    icon: ShoppingBag,
    category: 'Operations',
    route: '/purchases',
    permissions: ['purchase.read'],
    capabilities: ['procurement'],
    status: 'stable',
  },
  {
    id: 'accounting',
    name: 'Accounting',
    icon: Calculator,
    category: 'Finance',
    route: '/accounting',
    permissions: ['accounting.read'],
    capabilities: ['accounting', 'finance'],
    status: 'stable',
  },
  {
    id: 'accounts',
    name: 'Chart of Accounts',
    icon: BookOpen,
    category: 'Finance',
    route: '/accounting/accounts',
    permissions: ['accounting.accounts.read'],
    capabilities: ['accounting'],
    status: 'stable',
    dependencies: ['accounting'],
  },
  {
    id: 'journal',
    name: 'Journal Entries',
    icon: FileText,
    category: 'Finance',
    route: '/accounting/journal',
    permissions: ['accounting.journal.read'],
    capabilities: ['accounting'],
    status: 'stable',
    dependencies: ['accounting'],
  },
  {
    id: 'ledger',
    name: 'General Ledger',
    icon: BookOpen,
    category: 'Finance',
    route: '/accounting/ledger',
    permissions: ['accounting.journal.read'],
    capabilities: ['accounting'],
    status: 'stable',
    dependencies: ['accounting'],
  },
  {
    id: 'trial',
    name: 'Trial Balance',
    icon: Scale,
    category: 'Finance',
    route: '/accounting/trial-balance',
    permissions: ['accounting.journal.read'],
    capabilities: ['accounting'],
    status: 'stable',
    dependencies: ['accounting'],
  },
  {
    id: 'receivables',
    name: 'Receivables',
    icon: Banknote,
    category: 'Finance',
    route: '/accounting/receivables',
    permissions: ['accounting.receivables.read'],
    capabilities: ['accounting', 'finance'],
    status: 'stable',
    dependencies: ['accounting'],
  },
  {
    id: 'payables',
    name: 'Payables',
    icon: CreditCard,
    category: 'Finance',
    route: '/accounting/payables',
    permissions: ['accounting.payables.read'],
    capabilities: ['accounting', 'finance'],
    status: 'stable',
    dependencies: ['accounting'],
  },
  {
    id: 'payments',
    name: 'Payments',
    icon: Banknote,
    category: 'Finance',
    route: '/accounting/payments',
    permissions: ['payments.read'],
    capabilities: ['accounting', 'finance'],
    status: 'stable',
  },
  {
    id: 'employees',
    name: 'Employees',
    icon: Users2,
    category: 'People',
    route: '/users',
    permissions: ['employees.read'],
    capabilities: ['hr'],
    status: 'stable',
  },
  {
    id: 'payroll',
    name: 'Payroll',
    icon: Wallet,
    category: 'People',
    route: '/users',
    permissions: ['payroll.read'],
    capabilities: ['payroll', 'hr'],
    status: 'stable',
  },
  {
    id: 'roles',
    name: 'Roles & Access',
    icon: Shield,
    category: 'Administration',
    route: '/roles',
    permissions: ['organization.manage'],
    capabilities: ['administration'],
    status: 'stable',
  },
  {
    id: 'users',
    name: 'Users',
    icon: UsersRound,
    category: 'Administration',
    route: '/users',
    permissions: ['users.read'],
    capabilities: ['administration'],
    status: 'stable',
  },
  {
    id: 'audit',
    name: 'Audit Log',
    icon: History,
    category: 'Administration',
    route: '/audit',
    permissions: ['audit.read'],
    capabilities: ['administration'],
    status: 'stable',
  },
  {
    id: 'billing',
    name: 'Billing & Plan',
    icon: CreditCard,
    category: 'Administration',
    route: '/billing',
    permissions: ['billing.read'],
    capabilities: ['administration', 'platform'],
    status: 'stable',
  },
  {
    id: 'reports',
    name: 'Reports',
    icon: BarChart3,
    category: 'Analytics',
    route: '/dashboard',
    permissions: ['reports.read'],
    capabilities: ['reports', 'analytics'],
    status: 'stable',
  },
  {
    id: 'ai',
    name: 'AI Copilot',
    icon: Bot,
    category: 'Analytics',
    route: '/dashboard',
    permissions: ['ai.read'],
    capabilities: ['ai'],
    status: 'stable',
  },
];

export const MODULE_BY_ID: ReadonlyMap<string, ModuleManifest> = new Map(
  MODULE_MANIFESTS.map((m) => [m.id, m]),
);
