import {
  CookingPot,
  Stethoscope,
  Factory,
  GraduationCap,
  Laptop,
  Store,
  Pill,
  Scissors,
  Landmark,
  type LucideIcon,
} from 'lucide-react';

import type { IndustryKey } from '@/core/types';
import type { IndustryProfile, WidgetDefinition } from './types';

const baseFinancial: WidgetDefinition[] = [
  { key: 'revenueTrend', zone: 'charts', span: 8, permission: ['invoices.read', 'accounting.read', 'payments.read'] },
  { key: 'cashFlow', zone: 'charts', span: 4, permission: ['invoices.read', 'accounting.read', 'payments.read'] },
  { key: 'aiInsights', zone: 'insights', span: 12, aiRequired: true, permission: ['ai.read'] },
  { key: 'activity', zone: 'bottom', span: 7, permission: ['audit.read'] },
  { key: 'quickActions', zone: 'bottom', span: 5 },
  { key: 'healthScore', zone: 'side', span: 4 },
];

const restaurantWidgets: WidgetDefinition[] = [
  { key: 'metric', zone: 'hero', span: 3, source: 'todaySales', industries: ['restaurant'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'openOrders', industries: ['restaurant'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'activeTables', industries: ['restaurant'] },
  { key: 'metricCurrency', zone: 'hero', span: 3, source: 'averageTicket', industries: ['restaurant'] },
  { key: 'trend', zone: 'charts', span: 8, source: 'dailySales', industries: ['restaurant'], permission: ['sales.read'] },
  { key: 'donut', zone: 'charts', span: 4, source: 'menuMix', industries: ['restaurant'], permission: ['sales.read'] },
  { key: 'list', zone: 'side', span: 8, source: 'kitchenQueue', industries: ['restaurant'], permission: ['sales.read'] },
  ...baseFinancial,
];

const hospitalWidgets: WidgetDefinition[] = [
  { key: 'metric', zone: 'hero', span: 3, source: 'appointmentsToday', industries: ['hospital'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'admissions', industries: ['hospital'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'bedOccupancy', industries: ['hospital'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'emergencyCases', industries: ['hospital'] },
  { key: 'trend', zone: 'charts', span: 8, source: 'appointments', industries: ['hospital'], permission: ['sales.read'] },
  { key: 'donut', zone: 'charts', span: 4, source: 'departments', industries: ['hospital'], permission: ['employees.read'] },
  { key: 'list', zone: 'side', span: 8, source: 'medicineStock', industries: ['hospital'], permission: ['inventory.read'] },
  ...baseFinancial,
];

const manufacturingWidgets: WidgetDefinition[] = [
  { key: 'metric', zone: 'hero', span: 3, source: 'productionOutput', industries: ['manufacturing'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'machineUtilization', industries: ['manufacturing'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'workOrders', industries: ['manufacturing'] },
  { key: 'metricCurrency', zone: 'hero', span: 3, source: 'costPerUnit', industries: ['manufacturing'] },
  { key: 'trend', zone: 'charts', span: 8, source: 'production', industries: ['manufacturing'], permission: ['inventory.read'] },
  { key: 'donut', zone: 'charts', span: 4, source: 'quality', industries: ['manufacturing'], permission: ['inventory.read'] },
  { key: 'list', zone: 'side', span: 8, source: 'machineStatus', industries: ['manufacturing'] },
  ...baseFinancial,
];

const schoolWidgets: WidgetDefinition[] = [
  { key: 'metric', zone: 'hero', span: 3, source: 'enrolled', industries: ['school'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'attendanceToday', industries: ['school'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'feesCollected', industries: ['school'] },
  { key: 'metricCurrency', zone: 'hero', span: 3, source: 'expenditure', industries: ['school'] },
  { key: 'trend', zone: 'charts', span: 8, source: 'enrollment', industries: ['school'], permission: ['invoices.read', 'accounting.read', 'payments.read'] },
  { key: 'donut', zone: 'charts', span: 4, source: 'departments', industries: ['school'], permission: ['employees.read'] },
  { key: 'list', zone: 'side', span: 8, source: 'academicCalendar', industries: ['school'] },
  ...baseFinancial,
];

const softwareWidgets: WidgetDefinition[] = [
  { key: 'metric', zone: 'hero', span: 3, source: 'activeProjects', industries: ['software'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'sprintProgress', industries: ['software'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'openPRs', industries: ['software'] },
  { key: 'metricCurrency', zone: 'hero', span: 3, source: 'monthlyRecurringRevenue', industries: ['software'] },
  { key: 'trend', zone: 'charts', span: 8, source: 'recurringRevenue', industries: ['software'], permission: ['invoices.read', 'accounting.read', 'payments.read'] },
  { key: 'donut', zone: 'charts', span: 4, source: 'deployments', industries: ['software'] },
  { key: 'list', zone: 'side', span: 8, source: 'pullRequests', industries: ['software'] },
  { key: 'metricCurrency', zone: 'side', span: 4, source: 'aiTokens', industries: ['software'], aiRequired: true },
  ...baseFinancial.filter((w) => w.key !== 'quickActions'),
];

const retailWidgets: WidgetDefinition[] = [
  { key: 'metric', zone: 'hero', span: 3, source: 'posSalesToday', industries: ['retail'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'transactions', industries: ['retail'] },
  { key: 'metric', zone: 'hero', span: 3, source: 'productsInStock', industries: ['retail'] },
  { key: 'metricCurrency', zone: 'hero', span: 3, source: 'avgOrderValue', industries: ['retail'] },
  { key: 'trend', zone: 'charts', span: 8, source: 'dailySales', industries: ['retail'], permission: ['sales.read'] },
  { key: 'donut', zone: 'charts', span: 4, source: 'categorySales', industries: ['retail'], permission: ['sales.read'] },
  { key: 'list', zone: 'side', span: 8, source: 'lowStock', industries: ['retail'], permission: ['inventory.read'] },
  ...baseFinancial,
];

const genericWidgets: WidgetDefinition[] = [
  { key: 'metricCurrency', zone: 'hero', span: 3, source: 'monthlyRevenue' },
  { key: 'metric', zone: 'hero', span: 3, source: 'totalCustomers' },
  { key: 'metric', zone: 'hero', span: 3, source: 'openOrders' },
  { key: 'metric', zone: 'hero', span: 3, source: 'employees' },
  { key: 'trend', zone: 'charts', span: 8, source: 'revenue', permission: ['invoices.read', 'accounting.read', 'payments.read'] },
  { key: 'donut', zone: 'charts', span: 4, source: 'customers', permission: ['customers.read'] },
  { key: 'list', zone: 'side', span: 8, source: 'recentOrders' },
  ...baseFinancial,
];

export const INDUSTRY_PROFILES: Record<IndustryKey, IndustryProfile> = {
  restaurant: {
    id: 'restaurant',
    label: 'Restaurant & Food Service',
    shortLabel: 'Restaurant',
    description: 'Kitchen, front-of-house, tables, reservations and daily revenue.',
    icon: CookingPot,
    accent: '#f97316',
    widgets: restaurantWidgets,
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Service day in motion',
    subtitle: 'Kitchen, floor and revenue at a glance.',
    keywords: ['restaurant', 'kitchen', 'menu', 'tables', 'reservation', 'chef', 'service'],
  },
  hospital: {
    id: 'hospital',
    label: 'Hospital & Healthcare',
    shortLabel: 'Hospital',
    description: 'Appointments, admissions, bed occupancy and medicine stock.',
    icon: Stethoscope,
    accent: '#06b6d4',
    widgets: hospitalWidgets,
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Care operations at a glance',
    subtitle: 'Patients, departments and inventory in one view.',
    keywords: ['hospital', 'clinic', 'doctor', 'patient', 'medicine', 'appointment', 'care'],
  },
  manufacturing: {
    id: 'manufacturing',
    label: 'Manufacturing & Production',
    shortLabel: 'Manufacturing',
    description: 'Production output, machine utilisation, quality and procurement.',
    icon: Factory,
    accent: '#8b5cf6',
    widgets: manufacturingWidgets,
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Plant performance dashboard',
    subtitle: 'Production, machines and procurement in one view.',
    keywords: ['manufacturing', 'production', 'machine', 'factory', 'quality', 'procurement'],
  },
  school: {
    id: 'school',
    label: 'School & Education',
    shortLabel: 'School',
    description: 'Students, attendance, fee collection and the academic calendar.',
    icon: GraduationCap,
    accent: '#3b82f6',
    widgets: schoolWidgets,
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Academic operations at a glance',
    subtitle: 'Students, attendance and finances in one view.',
    keywords: ['school', 'college', 'university', 'student', 'teacher', 'attendance', 'exam'],
  },
  software: {
    id: 'software',
    label: 'Software Company',
    shortLabel: 'Software',
    description: 'Projects, sprints, pull requests, deployments and recurring revenue.',
    icon: Laptop,
    accent: '#6366f1',
    widgets: softwareWidgets,
    defaultModules: ['sales', 'accounting', 'crm', 'hr'],
    headline: 'Engineering velocity dashboard',
    subtitle: 'Projects, releases and recurring revenue in one view.',
    keywords: ['software', 'sprint', 'project', 'pull request', 'deployment', 'developer', 'startup'],
  },
  retail: {
    id: 'retail',
    label: 'Retail & Commerce',
    shortLabel: 'Retail',
    description: 'POS sales, transactions, products, stock and average order value.',
    icon: Store,
    accent: '#ec4899',
    widgets: retailWidgets,
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Point of sale command centre',
    subtitle: 'Sales, stock and customers in one view.',
    keywords: ['retail', 'shop', 'pos', 'store', 'sales floor', 'merchandise'],
  },
  pharmacy: {
    id: 'pharmacy',
    label: 'Pharmacy',
    shortLabel: 'Pharmacy',
    description: 'Prescriptions, medicine stock, dispensary and revenue.',
    icon: Pill,
    accent: '#10b981',
    widgets: [
      { key: 'metric', zone: 'hero', span: 3, source: 'prescriptionsToday', industries: ['pharmacy'] },
      { key: 'metric', zone: 'hero', span: 3, source: 'stockValue', industries: ['pharmacy'] },
      { key: 'metric', zone: 'hero', span: 3, source: 'expiringSoon', industries: ['pharmacy'] },
      { key: 'metricCurrency', zone: 'hero', span: 3, source: 'dailyRevenue', industries: ['pharmacy'] },
      { key: 'list', zone: 'side', span: 12, source: 'lowStock', industries: ['pharmacy'], permission: ['inventory.read'] },
      ...baseFinancial,
    ],
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Dispensary command centre',
    subtitle: 'Prescriptions, stock and revenue in one view.',
    keywords: ['pharmacy', 'prescription', 'medicine', 'dispensary', 'drug'],
  },
  garments: {
    id: 'garments',
    label: 'Garments & Textile',
    shortLabel: 'Garments',
    description: 'Orders, production lines, fabric stock and delivery.',
    icon: Scissors,
    accent: '#f43f5e',
    widgets: [
      { key: 'metric', zone: 'hero', span: 3, source: 'orderBook', industries: ['garments'] },
      { key: 'metric', zone: 'hero', span: 3, source: 'productionOutput', industries: ['garments'] },
      { key: 'metric', zone: 'hero', span: 3, source: 'fabricStock', industries: ['garments'] },
      { key: 'metric', zone: 'hero', span: 3, source: 'pendingDelivery', industries: ['garments'] },
      { key: 'list', zone: 'side', span: 12, source: 'productionLines', industries: ['garments'] },
      ...baseFinancial,
    ],
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Production floor overview',
    subtitle: 'Orders, lines and fabric stock in one view.',
    keywords: ['garments', 'textile', 'stitching', 'fabric', 'apparel', 'factory'],
  },
  'it-services': {
    id: 'it-services',
    label: 'IT Services',
    shortLabel: 'IT Services',
    description: 'Projects, tickets, clients and billable hours.',
    icon: Laptop,
    accent: '#0ea5e9',
    widgets: [
      { key: 'metric', zone: 'hero', span: 3, source: 'activeProjects', industries: ['it-services'] },
      { key: 'metric', zone: 'hero', span: 3, source: 'openTickets', industries: ['it-services'] },
      { key: 'metric', zone: 'hero', span: 3, source: 'billableHours', industries: ['it-services'] },
      { key: 'metricCurrency', zone: 'hero', span: 3, source: 'monthlyRetainer', industries: ['it-services'] },
      { key: 'trend', zone: 'charts', span: 8, source: 'recurringRevenue', industries: ['it-services'], permission: ['invoices.read', 'accounting.read', 'payments.read'] },
      { key: 'donut', zone: 'charts', span: 4, source: 'departments', industries: ['it-services'], permission: ['employees.read'] },
      { key: 'list', zone: 'side', span: 8, source: 'openTickets', industries: ['it-services'] },
      ...baseFinancial,
    ],
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Client delivery overview',
    subtitle: 'Projects, tickets and billable work in one view.',
    keywords: ['it', 'services', 'support', 'ticket', 'managed services', 'client'],
  },
  general: {
    id: 'general',
    label: 'General Business',
    shortLabel: 'Business',
    description: 'Core business metrics, finance and operations.',
    icon: Landmark,
    accent: '#3b82f6',
    widgets: genericWidgets,
    defaultModules: ['inventory', 'purchase', 'sales', 'accounting', 'crm', 'hr'],
    headline: 'Business overview',
    subtitle: 'Revenue, customers and operations in one view.',
    keywords: ['business', 'general', 'company', 'operations'],
  },
};

/** Industry → signature icon used in the workspace switcher. */
export const INDUSTRY_ICONS: Record<string, LucideIcon> = {
  restaurant: CookingPot,
  hospital: Stethoscope,
  manufacturing: Factory,
  school: GraduationCap,
  software: Laptop,
  retail: Store,
  pharmacy: Pill,
  garments: Scissors,
  'it-services': Laptop,
  general: Landmark,
};

export const INDUSTRY_LABELS: Record<string, string> = {
  restaurant: 'Restaurant',
  hospital: 'Hospital & Care',
  manufacturing: 'Manufacturing',
  school: 'School & Education',
  software: 'Software Company',
  retail: 'Retail',
  pharmacy: 'Pharmacy',
  garments: 'Garments & Textile',
  'it-services': 'IT Services',
  general: 'Business',
};
